<a href="https://colab.research.google.com/github/onecme/dataMining/blob/main/TI09_ElyasRandiRenaldi_0110223277_Pratikum3_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

##**Min-Max Normalization**

In [2]:
# Data contoh (ganti dengan data Anda)
data = np.array([[2.0, 5.0],
                [1.0, 4.0],
                [3.0, 6.0]])

# Inisaialisasi objek MinMaxScaler
Scaler = MinMaxScaler()

# Fit dan transformas data menggunaka Min-Max Scaling
Scaled_data = Scaler.fit_transform(data)

print("Data asli: ")
print(data)

print("\nData setelah Min-Max Scaling: ")
print(Scaled_data)

Data asli: 
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah Min-Max Scaling: 
[[0.5 0.5]
 [0.  0. ]
 [1.  1. ]]



##**Z-Score Transformation**

In [3]:
# Data contoh (ganti dengan data Anda)
data = np.array([[2.0, 5.0],
                [1.0, 4.0],
                [3.0, 6.0]])

# Inisialisasi objek StandardScaler
Scaler = StandardScaler()

# fit dan transformasi data menggunkan Z-Score Transformatin
Z_score_data = Scaler.fit_transform(data)

print("Data asli: ")
print(data)

print("\nData setelah Z-Score Transformation: ")
print(Z_score_data)

Data asli: 
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah Z-Score Transformation: 
[[ 0.          0.        ]
 [-1.22474487 -1.22474487]
 [ 1.22474487  1.22474487]]


##**Scaling Decimal**

In [4]:
# Data contoh (ganti dengan data anda)
data = np.array([200, 300, 400, 500, 600])

# Menentukan faktor penggerseran (scaling factor),
# misalnya 1000 untuk mengubah ke rentang 0-1
scaling_factor = 1000

# Melakukan transformasi Decimal Scaling
Scaled_data = data / scaling_factor

print("Data asli: ")
print(data)

print("\nData setelah Decimal Scaling: ")
print(Scaled_data)

Data asli: 
[200 300 400 500 600]

Data setelah Decimal Scaling: 
[0.2 0.3 0.4 0.5 0.6]
